---
lint:
  enabled: False
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master
    groups:
      - icinga2_master
  - name: client
    groups:
      - icinga2_client
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: goss
